# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix-sidecar-controller
description: The sidecar controller provides injection of the Atomix sidecar into Kubernetes pods.
kubeVersion: ">=1.17.0"
type: application
version: 2.0.0
keywords:
- atomix
home: https://atomix.io
maintainers:
- name: Jordan Halterman
  email: jordan.halterman@intel.com
