# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix-bench
description: Benchmarking Helm chart for Atomix
kubeVersion: ">=1.17.0"
type: application
version: 1.0.0
keywords:
- atomix
- performance
- benchmark
home: https://atomix.io
maintainers:
- name: Jordan Halterman
  email: jordan.halterman@intel.com
