# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix-shared-memory-controller
description: The shared memory controller extends the Kubernetes API with custom resources for memory stores.
kubeVersion: ">=1.17.0"
type: application
version: 2.0.0
keywords:
- atomix
- memory
- cache
home: https://atomix.io
maintainers:
- name: Jordan Halterman
  email: jordan.halterman@intel.com
