apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftmembers.multiraft.atomix.io
spec:
  group: multiraft.atomix.io
  names:
    kind: RaftMember
    listKind: RaftMemberList
    plural: raftmembers
    singular: raftmember
    shortNames:
      - rm
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - pod
                - type
              properties:
                pod:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                type:
                  type: string
                  default: Member
                  enum:
                    - Member
                    - Observer
                    - Witness
            status:
              type: object
              properties:
                podRef:
                  type: object
                  required:
                    - name
                    - uid
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    namespace:
                      type: string
                    name:
                      type: string
                    uid:
                      type: string
                version:
                  type: integer
                  nullable: true
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
                role:
                  type: string
                  enum:
                    - Follower
                    - Candidate
                    - Leader
                term:
                  type: integer
                  nullable: true
                leader:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                lastUpdated:
                  type: string
                  format: date-time
                lastSnapshotIndex:
                  type: integer
                  nullable: true
                lastSnapshotTime:
                  type: string
                  format: date-time
      additionalPrinterColumns:
        - name: Pod
          type: string
          description: The pod to which the member belongs
          jsonPath: .spec.pod.name
        - name: Type
          type: string
          description: The member type
          jsonPath: .spec.type
        - name: Role
          type: string
          description: The member role
          jsonPath: .status.role
        - name: Leader
          type: string
          description: The current leader on the member
          jsonPath: .status.leader.name
        - name: Term
          type: integer
          description: The current term on the member
          jsonPath: .status.term
        - name: Snapshot Index
          type: integer
          description: The index at which the member last took a snapshot
          jsonPath: .status.lastSnapshotIndex
        - name: Snapshot Time
          type: string
          description: The last time the member took a snapshot
          jsonPath: .status.lastSnapshotTime
        - name: Status
          type: string
          description: The member state
          jsonPath: .status.state