# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix-runtime-controller
description: The core Atomix runtime controller implements the Atomix Cloud runtime API
kubeVersion: ">=1.17.0"
type: application
version: 1.6.2
appVersion: v0.7.4
keywords:
- atomix
home: https://atomix.io
maintainers:
- name: Jordan Halterman
  email: jordan.halterman@intel.com
