# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix-controller
description: The core Atomix controller provides custom resources for Atomix data stores
kubeVersion: ">=1.17.0"
type: application
version: 2.0.0
appVersion: v0.7.7
keywords:
- atomix
home: https://atomix.io
maintainers:
- name: Jordan Halterman
  email: jordan.halterman@intel.com
