apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftgroups.multiraft.atomix.io
spec:
  group: multiraft.atomix.io
  names:
    kind: RaftGroup
    listKind: RaftGroupList
    plural: raftgroups
    singular: raftgroup
    shortNames:
      - rg
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                quorumSize:
                  type: integer
                  nullable: true
                readReplicas:
                  type: integer
                  nullable: true
                heartbeatPeriod:
                  type: string
                  nullable: true
                electionTimeout:
                  type: string
                  nullable: true
                snapshotEntryThreshold:
                  type: integer
                  minimum: 1
                  nullable: true
                compactionRetainEntries:
                  type: integer
                  minimum: 0
                  nullable: true
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
                term:
                  type: integer
                  nullable: true
                leader:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                followers:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
      additionalPrinterColumns:
        - name: Leader
          type: string
          description: The current leader for the group
          jsonPath: .status.leader.name
        - name: Term
          type: integer
          description: The current term for the group
          jsonPath: .status.term
        - name: Status
          type: string
          description: The group state
          jsonPath: .status.state