# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix-podmemory-controller
description: The pod memory controller extends the Kubernetes API with custom resources for pod-local shared memory stores.
kubeVersion: ">=1.17.0"
type: application
version: 2.0.0
appVersion: v0.1.0
keywords:
- atomix
- memory
home: https://atomix.io
maintainers:
- name: Jordan Halterman
  email: jordan.halterman@intel.com
