# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "atomix-runtime.fullname" . }}
webhooks:
- name: injector.broker.atomix.io
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: Namespaced
  clientConfig:
    service:
      name: atomix-runtime
      namespace: kube-system
      path: /inject-broker
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  failurePolicy: Ignore
  timeoutSeconds: 10
- name: injector.profile.atomix.io
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: Namespaced
  clientConfig:
    service:
      name: atomix-runtime
      namespace: kube-system
      path: /inject-profile
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  failurePolicy: Ignore
  timeoutSeconds: 10
- name: injector.driver.atomix.io
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: Namespaced
  clientConfig:
    service:
      name: atomix-runtime
      namespace: kube-system
      path: /inject-drivers
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  failurePolicy: Ignore
  timeoutSeconds: 10