# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ template "atomix-runtime-controller.fullname" . }}
  labels:
    name: {{ template "atomix-runtime-controller.fullname" . }}
spec:
  selector:
    name: {{ template "atomix-runtime-controller.fullname" . }}
  ports:
  - name: webhook
    port: 443
    targetPort: 443