# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Publish Docker Image

inputs:
  component:
    description: "The component to publish"
    required: true

  repository:
    description: "The name of the Docker repository"
    required: true

  username:
    description: "The Docker username"
    required: true

  password:
    description: "The Docker password"
    required: true

runs:
  using: composite
  steps:
    - id: parse-version
      name: Parse and validate version
      uses: ./.github/actions/version/parse-and-validate
      with:
        component: ${{ inputs.component }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push prerelease
      if: ${{ steps.parse-version.outputs.prerelease-version != "" }}
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.component }}
        file: ${{ inputs.component}}/${{ inputs.file }}
        tags: ${{ inputs.repository }}:v${{ steps.parse-version.outputs.prerelease-version }}
        push: true

    - name: Build and push patch
      if: ${{ steps.parse-version.outputs.prerelease-version == "" }}
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.component }}
        file: ${{ inputs.component}}/${{ inputs.file }}
        tags: ${{ inputs.repository }}:latest,${{ inputs.repository }}:v${{ steps.parse-version.outputs.patch-version }},${{ inputs.repository }}:v${{ steps.parse-version.outputs.minor-version }}
        push: true
