# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiraftclusters.raft.atomix.io
spec:
  group: raft.atomix.io
  scope: Namespaced
  names:
    kind: MultiRaftCluster
    listKind: MultiRaftClusterList
    plural: multiraftclusters
    singular: multiraftcluster
    shortNames:
      - mrc
  versions:
    - name: v1beta2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the cluster.
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  default: 1
                image:
                  type: string
                imagePullPolicy:
                  type: string
                  enum:
                    - Never
                    - IfNotPresent
                    - Always
                imagePullSecrets:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                securityContext:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                volumeClaimTemplate:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                config:
                  type: object
                  default: {}
                  properties:
                    rtt:
                      type: string
                      default: 10ms
                    server:
                      type: object
                      properties:
                        readBufferSize:
                          type: integer
                          nullable: true
                        writeBufferSize:
                          type: integer
                          nullable: true
                        maxSendMsgSize:
                          type: string
                          nullable: true
                        maxRecvMsgSize:
                          type: string
                          nullable: true
                        numStreamWorkers:
                          type: integer
                          nullable: true
                        maxConcurrentStreams:
                          type: integer
                          nullable: true
                    logging:
                      type: object
                      properties:
                        loggers:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              level:
                                type: string
                                nullable: true
                                enum:
                                  - debug
                                  - info
                                  - warn
                                  - error
                                  - fatal
                                  - panic
                              output:
                                type: object
                                additionalProperties:
                                  type: object
                                  properties:
                                    sink:
                                      type: string
                                    level:
                                      type: string
                                      nullable: true
                                      enum:
                                        - debug
                                        - info
                                        - warn
                                        - error
                                        - fatal
                                        - panic
                        sinks:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              encoding:
                                type: string
                                nullable: true
                                enum:
                                  - console
                                  - json
                              stdout:
                                type: object
                                properties: {}
                              stderr:
                                type: object
                                properties: {}
                              file:
                                type: object
                                properties:
                                  path:
                                    type: string
                                required:
                                  - path
            status:
              type: object
              default: {}
              properties:
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
                lastShardID:
                  type: integer
                partitionStatuses:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - partitionID
                      - shardID
                    properties:
                      name:
                        type: string
                      partitionID:
                        type: integer
                        minimum: 1
                      shardID:
                        type: integer
                        minimum: 1
      additionalPrinterColumns:
        - name: Replicas
          type: integer
          description: The number of replicas in the cluster
          jsonPath: .spec.replicas
        - name: Status
          type: string
          description: The cluster state
          jsonPath: .status.state