# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftstores.raft.atomix.io
spec:
  group: raft.atomix.io
  scope: Namespaced
  names:
    kind: RaftStore
    listKind: RaftStoreList
    plural: raftstores
    singular: raftstore
    shortNames:
      - rs
  versions:
    - name: v1beta2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the store.
              type: object
              properties:
                cluster:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                partitions:
                  type: integer
                  minimum: 1
                  maximum: 1024
                  default: 1
                replicationFactor:
                  type: integer
                  minimum: 1
                  maximum: 1024
                  nullable: true
                electionRTT:
                  type: integer
                  nullable: true
                heartbeatRTT:
                  type: integer
                  nullable: true
                snapshotEntries:
                  type: integer
                  nullable: true
                compactionOverhead:
                  type: integer
                  nullable: true
                maxInMemLogSize:
                  type: string
                  nullable: true
            status:
              type: object
              properties:
                replicationFactor:
                  type: integer
                state:
                  type: string
                  default: Initializing
                  enum:
                    - Initializing
                    - Reconfiguring
                    - Running
                    - Ready
      additionalPrinterColumns:
        - name: Cluster
          type: string
          description: The RaftCluster associated with the store
          jsonPath: .spec.cluster.name
        - name: Partitions
          type: integer
          description: The number of partitions in the store
          jsonPath: .spec.partitions
        - name: ReplicationFactor
          type: integer
          description: The number of replicas per partition
          jsonPath: .status.replicationFactor
        - name: Status
          type: string
          description: The store state
          jsonPath: .status.state