apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftpartitions.raft.atomix.io
spec:
  group: raft.atomix.io
  names:
    kind: RaftPartition
    listKind: RaftPartitionList
    plural: raftpartitions
    singular: raftpartition
    shortNames:
      - rp
  scope: Namespaced
  versions:
    - name: v1beta2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - cluster
                - partitionID
                - shardID
              properties:
                cluster:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 1024
                partitionID:
                  type: integer
                  minimum: 1
                  maximum: 1024
                shardID:
                  type: integer
                  minimum: 1
                electionRTT:
                  type: integer
                  nullable: true
                heartbeatRTT:
                  type: integer
                  nullable: true
                snapshotEntries:
                  type: integer
                  nullable: true
                compactionOverhead:
                  type: integer
                  nullable: true
                maxInMemLogSize:
                  type: string
                  nullable: true
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
                term:
                  type: integer
                  nullable: true
                leader:
                  type: integer
                  nullable: true
                followers:
                  type: array
                  items:
                    type: integer
                lastReplicaID:
                  type: integer
                memberStatuses:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - memberID
                      - replicaID
                    properties:
                      name:
                        type: string
                      memberID:
                        type: integer
                        minimum: 1
                        maximum: 1024
                      replicaID:
                        type: integer
                        minimum: 1
                      bootstrapped:
                        type: boolean
                      deleted:
                        type: boolean
      additionalPrinterColumns:
        - name: Partition
          type: integer
          description: The identifier of the partition
          jsonPath: .spec.partitionID
        - name: Shard
          type: integer
          description: The partition's shard identifier
          jsonPath: .spec.shardID
        - name: Cluster
          type: string
          description: The cluster in which the partition is stored
          jsonPath: .spec.cluster.name
        - name: Replicas
          type: integer
          description: The number of replicas in the partition
          jsonPath: .spec.replicas
        - name: Leader
          type: integer
          description: The current leader for the partition
          jsonPath: .status.leader
        - name: Term
          type: integer
          description: The current term for the partition
          jsonPath: .status.term
        - name: Status
          type: string
          description: The partition state
          jsonPath: .status.state