# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test Proxy

on:
  push:
    branches:
      - 'master'
    paths:
      - 'proxy/**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Go linter
        uses: ./.github/actions/go/lint
        with:
          component: proxy

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Go tests
        uses: ./.github/actions/go/test
        with:
          component: proxy

      - name: Build Docker image
        uses: ./.github/actions/docker/build
        with:
          component: proxy
          file: build/Dockerfile
