# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1

concurrency: 1

sampleInterval: 10s

writePercentage: .5

store:
  name: ""
  namespace: ""

primitive:
  kind: ""
  apiVersion: ""
  config: {}

image:
  repository: atomix/bench
  tag: ""
  pullPolicy: ""
  pullSecrets: []

logging:
  rootLevel: info
  encoding: console
  loggers:
    github.com/atomix/atomix/runtime/pkg/utils/grpc/interceptors:
      level: error

sidecar:
  image:
    repository: atomix/sidecar
    tag: ""
    pullPolicy: ""
    pullSecrets: []

  logging:
    rootLevel: info
    encoding: console
    loggers:
      github.com/atomix/atomix/runtime/pkg/utils/grpc/interceptors:
        level: error
