# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix-multi-raft-controller
description: The multi-raft controller extends the Kubernetes API with custom resources for multi-raft stores.
kubeVersion: ">=1.17.0"
type: application
version: 2.0.0
appVersion: v0.7.1
keywords:
- atomix
- multi-raft
- raft
home: https://atomix.io
maintainers:
- name: Jordan Halterman
  email: jordan.halterman@intel.com
