name: controller-release

on:
  push:
    tags:
      - 'controller/v*'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Release
        working-directory: controller
        run: make release
        env:
          TAG: ${{ github.ref_name }}
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish
        working-directory: controller
        run: |- 
          docker run -i \
            -v `pwd`:/build -w /build \
            -e GITHUB_TOKEN=${{ secrets.GH_TOKEN }} \
            --entrypoint ./build/release \
            quay.io/helmpack/chart-releaser:v1.4.0